spring.application.name=learning_backend
server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5432/learning_backend
spring.datasource.username=postgres
spring.datasource.password=22BCE3818

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.security.user.name=shreya
spring.security.user.password=22BCE3818